# Generated by Django 5.0.7 on 2024-09-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
