# Generated by Django 5.0.7 on 2024-09-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='signup_datetime',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
