# Generated by Django 5.0.7 on 2024-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_signup_signup_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='signup_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
