# Generated by Django 5.0.7 on 2024-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_signup_signup_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
