# Generated by Django 5.0.7 on 2024-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_signup_fname_alter_signup_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='fname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lname',
            field=models.CharField(max_length=60),
        ),
    ]
