# Generated by Django 5.0.2 on 2024-09-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='password',
        ),
    ]
